import Font from "../Font.js";

const DoubleStruck = new Font(3, "DoubleStruck");

/*DoubleStruck.initCharacterSet("italic",4);
DoubleStruck.character_sets["italic"].setCharacter("U+2145","D","ⅅ");
DoubleStruck.character_sets["italic"].setCharacter("U+2146","d","ⅆ");
DoubleStruck.character_sets["italic"].setCharacter("U+2147","e","ⅇ");
DoubleStruck.character_sets["italic"].setCharacter("U+2148","i","ⅈ");
DoubleStruck.character_sets["italic"].setCharacter("U+2149","j","ⅉ");
DoubleStruck.character_sets["italic"].setCharacter("U+2145","D","ⅅ");
DoubleStruck.character_sets["italic"].setCharacter("U+2146","d","ⅆ");
DoubleStruck.character_sets["italic"].setCharacter("U+2147","e","ⅇ");
DoubleStruck.character_sets["italic"].setCharacter("U+2148","i","ⅈ");
DoubleStruck.character_sets["italic"].setCharacter("U+2149","j","ⅉ");*/

DoubleStruck.initCharacterSet("normal", 5);
DoubleStruck.character_sets["normal"].setCharacter("U+1D538", "A", "𝔸");
DoubleStruck.character_sets["normal"].setCharacter("U+1D539", "B", "𝔹");
DoubleStruck.character_sets["normal"].setCharacter("U+1D53B", "D", "𝔻");
DoubleStruck.character_sets["normal"].setCharacter("U+1D53C", "E", "𝔼");
DoubleStruck.character_sets["normal"].setCharacter("U+1D53D", "F", "𝔽");
DoubleStruck.character_sets["normal"].setCharacter("U+1D53E", "G", "𝔾");
DoubleStruck.character_sets["normal"].setCharacter("U+1D540", "I", "𝕀");
DoubleStruck.character_sets["normal"].setCharacter("U+1D541", "J", "𝕁");
DoubleStruck.character_sets["normal"].setCharacter("U+1D542", "K", "𝕂");
DoubleStruck.character_sets["normal"].setCharacter("U+1D543", "L", "𝕃");
DoubleStruck.character_sets["normal"].setCharacter("U+1D544", "M", "𝕄");
DoubleStruck.character_sets["normal"].setCharacter("U+1D546", "O", "𝕆");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54A", "S", "𝕊");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54B", "T", "𝕋");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54C", "U", "𝕌");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54D", "V", "𝕍");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54E", "W", "𝕎");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54F", "X", "𝕏");
DoubleStruck.character_sets["normal"].setCharacter("U+1D550", "Y", "𝕐");
DoubleStruck.character_sets["normal"].setCharacter("U+1D552", "a", "𝕒");
DoubleStruck.character_sets["normal"].setCharacter("U+1D553", "b", "𝕓");
DoubleStruck.character_sets["normal"].setCharacter("U+1D554", "c", "𝕔");
DoubleStruck.character_sets["normal"].setCharacter("U+1D555", "d", "𝕕");
DoubleStruck.character_sets["normal"].setCharacter("U+1D556", "e", "𝕖");
DoubleStruck.character_sets["normal"].setCharacter("U+1D557", "f", "𝕗");
DoubleStruck.character_sets["normal"].setCharacter("U+1D558", "g", "𝕘");
DoubleStruck.character_sets["normal"].setCharacter("U+1D559", "h", "𝕙");
DoubleStruck.character_sets["normal"].setCharacter("U+1D55A", "i", "𝕚");
DoubleStruck.character_sets["normal"].setCharacter("U+1D55B", "j", "𝕛");
DoubleStruck.character_sets["normal"].setCharacter("U+1D55C", "k", "𝕜");
DoubleStruck.character_sets["normal"].setCharacter("U+1D55D", "l", "𝕝");
DoubleStruck.character_sets["normal"].setCharacter("U+1D55E", "m", "𝕞");
DoubleStruck.character_sets["normal"].setCharacter("U+1D55F", "n", "𝕟");
DoubleStruck.character_sets["normal"].setCharacter("U+1D560", "o", "𝕠");
DoubleStruck.character_sets["normal"].setCharacter("U+1D561", "p", "𝕡");
DoubleStruck.character_sets["normal"].setCharacter("U+1D562", "q", "𝕢");
DoubleStruck.character_sets["normal"].setCharacter("U+1D563", "r", "𝕣");
DoubleStruck.character_sets["normal"].setCharacter("U+1D564", "s", "𝕤");
DoubleStruck.character_sets["normal"].setCharacter("U+1D565", "t", "𝕥");
DoubleStruck.character_sets["normal"].setCharacter("U+1D566", "u", "𝕦");
DoubleStruck.character_sets["normal"].setCharacter("U+1D567", "v", "𝕧");
DoubleStruck.character_sets["normal"].setCharacter("U+1D568", "w", "𝕨");
DoubleStruck.character_sets["normal"].setCharacter("U+1D569", "x", "𝕩");
DoubleStruck.character_sets["normal"].setCharacter("U+1D56A", "y", "𝕪");
DoubleStruck.character_sets["normal"].setCharacter("U+1D56B", "z", "𝕫");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7D8", "0", "𝟘");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7D9", "1", "𝟙");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7DA", "2", "𝟚");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7DB", "3", "𝟛");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7DC", "4", "𝟜");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7DD", "5", "𝟝");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7DE", "6", "𝟞");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7DF", "7", "𝟟");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7E0", "8", "𝟠");
DoubleStruck.character_sets["normal"].setCharacter("U+1D7E1", "9", "𝟡");
DoubleStruck.character_sets["normal"].setCharacter("U+1D54A", "S", "𝕊");
DoubleStruck.character_sets["normal"].setCharacter("U+2102", "C", "ℂ");
DoubleStruck.character_sets["normal"].setCharacter("U+210D", "H", "ℍ");
DoubleStruck.character_sets["normal"].setCharacter("U+2115", "N", "ℕ");
DoubleStruck.character_sets["normal"].setCharacter("U+2119", "P", "ℙ");
DoubleStruck.character_sets["normal"].setCharacter("U+211A", "Q", "ℚ");
DoubleStruck.character_sets["normal"].setCharacter("U+211D", "R", "ℝ");
DoubleStruck.character_sets["normal"].setCharacter("U+2124", "Z", "ℤ");
DoubleStruck.character_sets["normal"].setCharacter("U+2124", "Z", "ℤ");
DoubleStruck.character_sets["normal"].setCharacter("U+2115", "N", "ℕ");
DoubleStruck.character_sets["normal"].setCharacter("U+2119", "P", "ℙ");
DoubleStruck.character_sets["normal"].setCharacter("U+211A", "Q", "ℚ");
DoubleStruck.character_sets["normal"].setCharacter("U+211D", "R", "ℝ");
DoubleStruck.character_sets["normal"].setCharacter("U+2102", "C", "ℂ");
DoubleStruck.character_sets["normal"].setCharacter("U+210D", "H", "ℍ");
DoubleStruck.character_sets["normal"].setCharacter("U+2102", "C", "ℂ");
DoubleStruck.character_sets["normal"].setCharacter("U+210D", "H", "ℍ");
DoubleStruck.character_sets["normal"].setCharacter("U+2115", "N", "ℕ");
DoubleStruck.character_sets["normal"].setCharacter("U+2119", "P", "ℙ");
DoubleStruck.character_sets["normal"].setCharacter("U+211A", "Q", "ℚ");
DoubleStruck.character_sets["normal"].setCharacter("U+211D", "R", "ℝ");
DoubleStruck.character_sets["normal"].setCharacter("U+2124", "Z", "ℤ");

export default DoubleStruck;