import Font from "../Font.js";

const Typewriter = new Font(218,"Typewriter");

Typewriter.initCharacterSet("normal",219);
Typewriter.character_sets["normal"].setCharacter(null,"A","𝙰");
Typewriter.character_sets["normal"].setCharacter(null,"B","𝙱");
Typewriter.character_sets["normal"].setCharacter(null,"C","𝙲");
Typewriter.character_sets["normal"].setCharacter(null,"D","𝙳");
Typewriter.character_sets["normal"].setCharacter(null,"E","𝙴");
Typewriter.character_sets["normal"].setCharacter(null,"F","𝙵");
Typewriter.character_sets["normal"].setCharacter(null,"G","𝙶");
Typewriter.character_sets["normal"].setCharacter(null,"H","𝙷");
Typewriter.character_sets["normal"].setCharacter(null,"I","𝙸");
Typewriter.character_sets["normal"].setCharacter(null,"J","𝙹");
Typewriter.character_sets["normal"].setCharacter(null,"K","𝙺");
Typewriter.character_sets["normal"].setCharacter(null,"L","𝙻");
Typewriter.character_sets["normal"].setCharacter(null,"M","𝙼");
Typewriter.character_sets["normal"].setCharacter(null,"N","𝙽");
Typewriter.character_sets["normal"].setCharacter(null,"O","𝙾");
Typewriter.character_sets["normal"].setCharacter(null,"P","𝙿");
Typewriter.character_sets["normal"].setCharacter(null,"Q","𝚀");
Typewriter.character_sets["normal"].setCharacter(null,"R","𝚁");
Typewriter.character_sets["normal"].setCharacter(null,"S","𝚂");
Typewriter.character_sets["normal"].setCharacter(null,"T","𝚃");
Typewriter.character_sets["normal"].setCharacter(null,"U","𝚄");
Typewriter.character_sets["normal"].setCharacter(null,"V","𝚅");
Typewriter.character_sets["normal"].setCharacter(null,"W","𝚆");
Typewriter.character_sets["normal"].setCharacter(null,"X","𝚇");
Typewriter.character_sets["normal"].setCharacter(null,"Y","𝚈");
Typewriter.character_sets["normal"].setCharacter(null,"Z","𝚉");
Typewriter.character_sets["normal"].setCharacter(null,"a","𝚊");
Typewriter.character_sets["normal"].setCharacter(null,"b","𝚋");
Typewriter.character_sets["normal"].setCharacter(null,"c","𝚌");
Typewriter.character_sets["normal"].setCharacter(null,"d","𝚍");
Typewriter.character_sets["normal"].setCharacter(null,"e","𝚎");
Typewriter.character_sets["normal"].setCharacter(null,"f","𝚏");
Typewriter.character_sets["normal"].setCharacter(null,"g","𝚐");
Typewriter.character_sets["normal"].setCharacter(null,"h","𝚑");
Typewriter.character_sets["normal"].setCharacter(null,"i","𝚒");
Typewriter.character_sets["normal"].setCharacter(null,"j","𝚓");
Typewriter.character_sets["normal"].setCharacter(null,"k","𝚔");
Typewriter.character_sets["normal"].setCharacter(null,"l","𝚕");
Typewriter.character_sets["normal"].setCharacter(null,"m","𝚖");
Typewriter.character_sets["normal"].setCharacter(null,"n","𝚗");
Typewriter.character_sets["normal"].setCharacter(null,"o","𝚘");
Typewriter.character_sets["normal"].setCharacter(null,"p","𝚙");
Typewriter.character_sets["normal"].setCharacter(null,"q","𝚚");
Typewriter.character_sets["normal"].setCharacter(null,"r","𝚛");
Typewriter.character_sets["normal"].setCharacter(null,"s","𝚜");
Typewriter.character_sets["normal"].setCharacter(null,"t","𝚝");
Typewriter.character_sets["normal"].setCharacter(null,"u","𝚞");
Typewriter.character_sets["normal"].setCharacter(null,"v","𝚟");
Typewriter.character_sets["normal"].setCharacter(null,"w","𝚠");
Typewriter.character_sets["normal"].setCharacter(null,"x","𝚡");
Typewriter.character_sets["normal"].setCharacter(null,"y","𝚢");
Typewriter.character_sets["normal"].setCharacter(null,"z","𝚣");
Typewriter.character_sets["normal"].setCharacter(null,"0","𝟶");
Typewriter.character_sets["normal"].setCharacter(null,"1","𝟷");
Typewriter.character_sets["normal"].setCharacter(null,"2","𝟸");
Typewriter.character_sets["normal"].setCharacter(null,"3","𝟹");
Typewriter.character_sets["normal"].setCharacter(null,"4","𝟺");
Typewriter.character_sets["normal"].setCharacter(null,"5","𝟻");
Typewriter.character_sets["normal"].setCharacter(null,"6","𝟼");
Typewriter.character_sets["normal"].setCharacter(null,"7","𝟽");
Typewriter.character_sets["normal"].setCharacter(null,"8","𝟾");
Typewriter.character_sets["normal"].setCharacter(null,"9","𝟿");

export default Typewriter;